/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BGBrSQFABZy
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function EODItem() {
  return (
    <div className="container mx-auto my-8 px-4 sm:px-6 lg:px-8">
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold">End of Day Report</h1>
          <p className="text-muted-foreground">Construction Site, August 18, 2024</p>
        </div>
        <div>
          <h2 className="text-2xl font-bold">Site Attendance</h2>
          <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <div className="rounded-lg border bg-card p-4">
              <h3 className="text-lg font-medium">Site Manager</h3>
              <div className="mt-2 text-muted-foreground">
                <p>Emily Nguyen</p>
                <p>In: 8:00 AM, Out: 6:00 PM</p>
              </div>
            </div>
            <div className="rounded-lg border bg-card p-4">
              <h3 className="text-lg font-medium">Safety Officer</h3>
              <div className="mt-2 text-muted-foreground">
                <p>Michael Lee</p>
                <p>In: 8:30 AM, Out: 5:30 PM</p>
              </div>
            </div>
            <div className="rounded-lg border bg-card p-4">
              <h3 className="text-lg font-medium">Project Coordinator</h3>
              <div className="mt-2 text-muted-foreground">
                <p>Sophia Patel</p>
                <p>In: 9:00 AM, Out: 6:30 PM</p>
              </div>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-bold">Material Inventory Log</h2>
          <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <div className="rounded-lg border bg-card p-4">
              <h3 className="text-lg font-medium">Concrete</h3>
              <div className="mt-2 text-muted-foreground">
                <p>10:50 AM - 20 cubic meters used</p>
                <p>11:50 AM - 15 cubic meters added</p>
                <p>Current Inventory: 35 cubic meters</p>
              </div>
            </div>
            <div className="rounded-lg border bg-card p-4">
              <h3 className="text-lg font-medium">Steel Beams</h3>
              <div className="mt-2 text-muted-foreground">
                <p>9:30 AM - 5 units used</p>
                <p>1:00 PM - 10 units added</p>
                <p>Current Inventory: 20 units</p>
              </div>
            </div>
            <div className="rounded-lg border bg-card p-4">
              <h3 className="text-lg font-medium">Bricks</h3>
              <div className="mt-2 text-muted-foreground">
                <p>8:00 AM - 500 units used</p>
                <p>2:30 PM - 1,000 units added</p>
                <p>Current Inventory: 5,500 units</p>
              </div>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-bold">Photos Uploaded</h2>
          <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <div className="rounded-lg border bg-card p-4">
              <img
                src="/placeholder.svg"
                alt="Photo 1"
                width="300"
                height="200"
                className="w-full object-cover rounded-lg"
                style={{ aspectRatio: "300/200", objectFit: "cover" }}
              />
            </div>
            <div className="rounded-lg border bg-card p-4">
              <img
                src="/placeholder.svg"
                alt="Photo 2"
                width="300"
                height="200"
                className="w-full object-cover rounded-lg"
                style={{ aspectRatio: "300/200", objectFit: "cover" }}
              />
            </div>
            <div className="rounded-lg border bg-card p-4">
              <img
                src="/placeholder.svg"
                alt="Photo 3"
                width="300"
                height="200"
                className="w-full object-cover rounded-lg"
                style={{ aspectRatio: "300/200", objectFit: "cover" }}
              />
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-bold">Worker Logs</h2>
          <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <div className="rounded-lg border bg-card p-4">
              <h3 className="text-lg font-medium">Masons</h3>
              <p className="mt-2 text-muted-foreground">10 workers</p>
            </div>
            <div className="rounded-lg border bg-card p-4">
              <h3 className="text-lg font-medium">Electricians</h3>
              <p className="mt-2 text-muted-foreground">6 workers</p>
            </div>
            <div className="rounded-lg border bg-card p-4">
              <h3 className="text-lg font-medium">Carpenters</h3>
              <p className="mt-2 text-muted-foreground">8 workers</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
