"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zTa682IuJQW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Options() {
  return (
    <main className="flex h-screen w-full items-center justify-center bg-background">
      <div className="flex w-full max-w-2xl flex-col gap-4 px-4 md:flex-row">
        <Link
          href="#"
          className="flex-1 rounded-lg bg-primary p-8 text-center text-2xl font-bold text-primary-foreground transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
          prefetch={false}
        >
          Users
        </Link>
        <Link
          href="#"
          className="flex-1 rounded-lg bg-primary p-8 text-center text-2xl font-bold text-primary-foreground transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
          prefetch={false}
        >
          Site
        </Link>
      </div>
    </main>
  )
}
