/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1x6ojcKWbx9
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"

export function UserDetails() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-6xl mx-auto p-4 md:p-8">
      <div className="flex flex-col gap-6">
        <div className="flex items-center gap-4">
          <Avatar className="h-20 w-20">
            <AvatarImage src="/placeholder-user.jpg" alt="@username" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <div className="grid gap-1">
            <h2 className="text-2xl font-bold">John Doe</h2>
            <p className="text-muted-foreground">Software Engineer</p>
          </div>
        </div>
        <Card>
          <CardHeader>
            <CardTitle>Attendance Details</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-6">
            <div className="grid gap-2">
              <div className="text-sm font-medium">Current Month</div>
              <div className="grid grid-cols-1 gap-2 text-center">
                {Array.from({ length: 31 }, (_, i) => i + 1).map((day) => (
                  <div key={day} className="rounded-md py-1 bg-muted text-muted-foreground">
                    <div className="flex justify-between">
                      <span>{day}</span>
                      <span>9:15 AM</span>
                      <span>6:30 PM</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div className="grid gap-2" />
          </CardContent>
        </Card>
      </div>
      <div className="flex flex-col gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Attendance Summary</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="flex flex-col items-center gap-1 bg-muted p-4 rounded-lg">
                <div className="text-4xl font-bold">92%</div>
                <div className="text-sm text-muted-foreground">Attendance Rate</div>
              </div>
              <div className="flex flex-col items-center gap-1 bg-muted p-4 rounded-lg">
                <div className="text-4xl font-bold">22</div>
                <div className="text-sm text-muted-foreground">Days Present</div>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="flex flex-col items-center gap-1 bg-muted p-4 rounded-lg">
                <div className="text-4xl font-bold">9:15 AM</div>
                <div className="text-sm text-muted-foreground">Average Check-in</div>
              </div>
              <div className="flex flex-col items-center gap-1 bg-muted p-4 rounded-lg">
                <div className="text-4xl font-bold">6:30 PM</div>
                <div className="text-sm text-muted-foreground">Average Check-out</div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
